id: P5EE53F96
initial_creation_type: ocr
source_metadata:
  volumes:
    23d74ff597a8433cb6c1d914bcd795aa:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: རལ་པ་གཅིག་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
